plugins {
	id 'net.fabricmc.fabric-loom' version "${loom_version}"
	id 'io.github.ladysnake.chenille' version "${chenille_version}"
	id 'maven-publish'
}

version = project.mod_version
group = project.maven_group

base {
	archivesName = project.archives_base_name
}

repositories {
	mavenLocal()
	mavenCentral()
	chenille.repositories.ladysnake()
	chenille.repositories.modrinth()
}

loom {
	accessWidenerPath = file("src/main/resources/ntrdeals_items.classtweaker")
}

fabricApi {
	configureDataGeneration {
		client = true
	}
}

dependencies {
	minecraft "com.mojang:minecraft:${project.minecraft_version}"
	implementation "net.fabricmc:fabric-loader:${project.loader_version}"
	implementation "net.fabricmc.fabric-api:fabric-api:${project.fabric_api_version}"

	//compile mods
	includeImplementation "io.github.nottherealdeal:realapi:${project.realapi_version}"
//	include "io.github.nottherealdeal:realapi:${project.realapi_version}"

	includeImplementation "org.ladysnake.cardinal-components-api:cardinal-components-base:${project.cca_version}"
	includeImplementation "org.ladysnake.cardinal-components-api:cardinal-components-entity:${project.cca_version}"
//	include "org.ladysnake.cardinal-components-api:cardinal-components-base:${project.cca_version}"
//	include "org.ladysnake.cardinal-components-api:cardinal-components-entity:${project.cca_version}"

	//runtime mods
	runtimeOnly "maven.modrinth:modmenu:${project.modmenu_version}"
	runtimeOnly "maven.modrinth:carpet:${project.carpet_version}"
	runtimeOnly "maven.modrinth:sodium:${project.sodium_version}"
//	runtimeOnly "maven.modrinth:jei:${project.jei_version}"
//	runtimeOnly "maven.modrinth:enchancement:${project.enchancement_version}"
//	runtimeOnly "maven.modrinth:strawberrylib:${project.strawberrylib_version}"
}

processResources {
	inputs.property "version", project.version

	filesMatching("fabric.mod.json") {
		expand "version": inputs.properties.version
	}
}

tasks.withType(JavaCompile).configureEach {
	it.options.release = 25
}

java {
	withSourcesJar()

	sourceCompatibility = JavaVersion.VERSION_25
	targetCompatibility = JavaVersion.VERSION_25
}

jar {
	inputs.property "archivesName", project.base.archivesName

	from("LICENSE") {
		rename { "${it}_${inputs.properties.archivesName}"}
	}
}

publishing {
	publications {
		create("mavenJava", MavenPublication) {
			groupId = project.maven_group
			artifactId = project.archives_base_name
			version = project.version

			from components.java
		}
	}

	repositories {
		mavenLocal()
	}
}