plugins {
	id 'net.fabricmc.fabric-loom' version "${loom_version}"
	id 'io.github.ladysnake.chenille' version "${chenille_version}"
	id 'maven-publish'
}

version = project.mod_version
group = project.maven_group

repositories {
	mavenLocal()
	mavenCentral()
	chenille.repositories.ladysnake()
	chenille.repositories.up()
	chenille.repositories.modrinth()
}

loom {
	accessWidenerPath = file("src/main/resources/ntrdeals_items.classtweaker")
}

fabricApi {
	configureDataGeneration {
		client = true
	}
}

dependencies {
	minecraft "com.mojang:minecraft:${project.minecraft_version}"
	implementation "net.fabricmc:fabric-loader:${project.loader_version}"
	implementation "net.fabricmc.fabric-api:fabric-api:${project.fabric_api_version}"

	//compile mods
	includeImplementation "io.github.nottherealdeal:realapi:${project.realapi_version}"
	includeImplementation "org.ladysnake.cardinal-components-api:cardinal-components-base:${project.cca_version}"
	includeImplementation "org.ladysnake.cardinal-components-api:cardinal-components-entity:${project.cca_version}"

	compileOnly "moriyashiine.strawberrylib:strawberrylib-fabric:${project.compile_strawberrylib_version}"
	compileOnly "moriyashiine.enchancement:enchancement-fabric:${project.compile_enchancement_version}"

	//runtime mods
	runtimeOnly "maven.modrinth:mOgUt4GM:${project.modmenu_version}"
//	runtimeOnly "maven.modrinth:TQTTVgYE:${project.carpet_version}"
//	runtimeOnly "maven.modrinth:l6YH9Als:${project.spark_version}"
	runtimeOnly "maven.modrinth:AANobbMI:${project.sodium_version}"
	runtimeOnly "maven.modrinth:u6dRKJwZ:${project.jei_version}"
	runtimeOnly "maven.modrinth:9Ya7Yyre:${project.runtime_strawberrylib_version}"
	runtimeOnly "maven.modrinth:6hN1V6wJ:${project.runtime_enchancement_version}"
}

processResources {
	inputs.property "version", project.version

	filesMatching("fabric.mod.json") {
		expand "version": inputs.properties.version
	}
}

tasks.withType(JavaCompile).configureEach {
	it.options.release = 25
}

java {
	withSourcesJar()

	sourceCompatibility = JavaVersion.VERSION_25
	targetCompatibility = JavaVersion.VERSION_25
}

jar {
	def projectName = project.name
	inputs.property "projectName", projectName

	from("LICENSE") {
		rename { "${it}_$projectName"}
	}
}

publishing {
	publications {
		create("mavenJava", MavenPublication) {
			groupId = project.maven_group
			artifactId = project.name
			version = project.version

			from components.java
		}
	}

	repositories {
		mavenLocal()
	}
}