org.gradle.jvmargs=-Xmx8G
org.gradle.parallel=true
org.gradle.configuration-cache=false

minecraft_version=26.2
loader_version=0.19.3
loom_version=1.17-SNAPSHOT
chenille_version=0.18.0

mod_version=3.1.0
maven_group=io.github.nottherealdeal
archives_base_name=ntrdeals_items

#compile mods:
fabric_api_version=0.152.2+26.2
realapi_version=0.4.62
cca_version = 8.0.0

#runtime mods:
modmenu_version=20.0.0-beta.2
carpet_version=26.2
sodium_version=mc26.2-0.9.0-fabric
#jei_version=29.5.0.28
enchancement_version=26.2-r2
strawberrylib_version=26.2-r1