#gradle:
org.gradle.jvmargs=-Xmx8G
org.gradle.parallel=true
org.gradle.configuration-cache=true

loom_version=1.18-SNAPSHOT
chenille_version=0.22.1

#mod:
version=3.3.1
group=io.github.nottherealdeal

#compile:
loader_version=0.19.5
minecraft_version=26.3
fabric_api_version=0.161.0+26.3
realapi_version=0.4.100
cca_version = 8.1.0
compile_strawberrylib_version=26.3-r1
compile_enchancement_version=26.3-r2

#runtime:
modmenu_version=kyy7dbrZ
carpet_version=yt9oDFOj
spark_version=e3hsPc1o
sodium_version=v4PSXean
jei_version=pjjNQBoS
runtime_strawberrylib_version=OoMuF3O2
runtime_enchancement_version=XNlOiyDC