org.gradle.jvmargs=-Xmx8G
org.gradle.parallel=true
org.gradle.configuration-cache=false

minecraft_version=26.3
loader_version=0.19.5
loom_version=1.17-SNAPSHOT
chenille_version=0.18.0

mod_version=3.2.0
maven_group=io.github.nottherealdeal

#compile mods:
fabric_api_version=0.160.5+26.3
realapi_version=0.4.94
cca_version = 8.0.1

compile_enchancement_version=26.3-r1
compile_strawberrylib_version=26.3-r1

#runtime mods:
modmenu_version=lcxkZSq6
carpet_version=bGrLxJ8v
spark_version=iYFOl6lQ
sodium_version=bAZQdGpg
jei_version=cHLRHO2W
runtime_enchancement_version=xy16atmP
runtime_strawberrylib_version=OoMuF3O2